sast: # Suite name
  # General configuration section
  test_type: "SAST"
  project_name: "DevSecOps" # the name of the project used in reports
  environment: "staging"   # literal name of environment (e.g. prod/stage/etc.)

  # Reporting configuration section (all report types are optional)
  html_report: true           # do you need an html report (true/false)

  # Code scanning
  language: java  # supported: python, ruby, java, nodejs, golang
